# Generated by Django 4.0.3 on 2022-03-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
